apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: rabbit-argo-application
  namespace: argocd
spec:
  project: default

  source:
    repoURL: https://github.com/art-romaniuk/rabbit
    path: helm-charts/test
    targetRevision: HEAD
    helm:
      valueFiles:
        - values.yaml
      volumePermissions:
        enabled: false

  destination:
    server: https://kubernetes.default.svc

  syncPolicy:
    syncOptions:
      - Validate=false
