apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: rabbit-argo-application
  namespace: default
psec:
  project: rabbit-argo

  source:
    repoURL: https://github.com/art-romaniuk/rabbit
    targetRevision: HEAD
    path: helm-charts
  destination:
    server: https://kubernetes.default.svc

  syncPolicy:
    automated:
      selfHearl: true
      prune: true
